const lang = "es";
const translate = (word) => {

    switch (word.toLowerCase()) {
        case 'name': return (lang == 'es') ? 'Nombre' : 'Name'; break;
        case 'full name': return (lang == 'es') ? 'Nombre completo' : 'Full name'; break;
        case 'email': return (lang == 'es') ? 'Correo' : 'Email'; break;
        case 'email address': return (lang == 'es') ? 'Dirección de correo' : 'Email address'; break;
        case 'phone': return (lang == 'es') ? 'Telefono' : 'Phone'; break;
        case 'phone number': return (lang == 'es') ? 'Número Telefónico' : 'Phone number'; break;
        case 'address': return (lang == 'es') ? 'Dirección' : 'Address'; break;
        case 'status': return (lang == 'es') ? 'Estatus' : 'Status'; break;
        case 'customers': return (lang == 'es') ? 'Clientes' : 'Customers'; break;
        case 'users': return (lang == 'es') ? 'Usuarios' : 'Users'; break;
        case 'user': return (lang == 'es') ? 'Usuario' : 'User'; break;
        case 'deleted': return (lang == 'es') ? 'Borrado' : 'Deleted'; break;
        case 'active': return (lang == 'es') ? 'Activo' : 'Active'; break;
        case 'deactive': return (lang == 'es') ? 'Desactivar' : 'Deactive'; break;
        case 'management': return (lang == 'es') ? 'Administrar' : 'Management'; break;
        case 'rol': return (lang == 'es') ? 'Perfil' : 'rol'; break;
        case 'language': return (lang == 'es') ? 'Lenguaje' : 'Language'; break;
        case 'summary': return (lang == 'es') ? 'Resumen' : 'Summary'; break;
        case 'view summary': return (lang == 'es') ? 'Ver Resumen' : 'View Summary'; break;
        case 'dni': return (lang == 'es') ? 'Nro Documento' : 'Dni'; break;
        case 'agree terms': return (lang == 'es') ? 'Acepto Terminos' : 'Agree Terms'; break;
        case 'disabled': return (lang == 'es') ? 'Deshabilitado' : 'Disabled'; break;
        case 'isactive': return (lang == 'es') ? 'Esta activo' : 'isActive'; break;
        case 'franchise venues': return (lang == 'es') ? 'Sucursales' : 'Franchise venues'; break;
        case 'franchise': return (lang == 'es') ? 'Franquicia' : 'Franchise'; break;
        case 'venue': return (lang == 'es') ? 'Sucursal' : 'Venue'; break;
        case 'estimated time': return (lang == 'es') ? ' tiempo estimado' : 'Estimated time'; break;
        case 'price': return (lang == 'es') ? 'Precio' : 'Price'; break;
        case 'service': return (lang == 'es') ? 'Servicio' : 'Service'; break;
        case 'pack': return (lang == 'es') ? 'Paquete' : 'Pack'; break;
        case 'time': return (lang == 'es') ? 'Tiempo' : 'Time'; break;
        case 'description': return (lang == 'es') ? 'Descripción' : 'Description'; break;
        case 'service list': return (lang == 'es') ? 'Lista de servicios' : 'Service list'; break;
        case 'service info': return (lang == 'es') ? 'Información del servicio' : 'Service info'; break;
        case 'template': return (lang == 'es') ? 'Plantilla' : 'Template'; break;
        case 'availabilities': return (lang == 'es') ? 'Disponibilidades' : 'Availabilities'; break;
        case 'venue': return (lang == 'es') ? 'Sucursal' : 'Venue'; break;
        case 'venue name': return (lang == 'es') ? 'Nombre de sucursal' : 'Venue name'; break;
        case 'venues': return (lang == 'es') ? 'Sucursales' : 'Venues'; break;
        case 'venue info': return (lang == 'es') ? 'Información de la sucursal' : 'Venue info'; break;
        case 'venue list': return (lang == 'es') ? 'Lista de sucursales' : 'Venues list'; break;
        case 'sucursal name': return (lang == 'es') ? 'Nombre de sucursal' : 'Sucursal name'; break;
        case 'prowasher name': return (lang == 'es') ? 'Nombre de prowasher' : 'Prowasher name'; break;
        case 'franchise name': return (lang == 'es') ? 'Nombre de franquicia' : 'Franchise name'; break;
        case 'direction': return (lang == 'es') ? 'Dirección' : 'Direction'; break;
        case 'date': return (lang == 'es') ? 'Fecha' : 'Date'; break;
        case 'order list': return (lang == 'es') ? 'Lista de ordenes' : 'Order list'; break;
        case 'orders': return (lang == 'es') ? 'Ordenes' : 'Orders'; break;
        case 'service date': return (lang == 'es') ? 'Día del servicio' : 'Service day'; break;
        case 'card brand': return (lang == 'es') ? 'Marca del vehiculo' : 'Card brand'; break;
        case 'card category': return (lang == 'es') ? 'Categoria del vehiculo' : 'Card category'; break;
        case 'card model': return (lang == 'es') ? 'Modelo del vehiculo' : 'Card model'; break;
        case 'card patent': return (lang == 'es') ? 'Patente del vehiculo' : 'Card patent'; break;
        case 'amount': return (lang == 'es') ? 'Monto' : 'Amount'; break;
        case 'expiration date': return (lang == 'es') ? 'Fecha de expiración' : 'Expiration date'; break;
        case 'code': return (lang == 'es') ? 'Codigo' : 'Code'; break;
        case 'comment': return (lang == 'es') ? 'Comentario' : 'Comment'; break;
        case 'evaluation comment': return (lang == 'es') ? 'Comentario de evaluación' : 'Evaluation comment'; break;
        case 'evaluation rate': return (lang == 'es') ? 'Valoración de evaluación' : 'Evaluation rate'; break;
        case 'indications': return (lang == 'es') ? 'Indicaciones' : 'Indications'; break;
        case 'total price': return (lang == 'es') ? 'Precio total' : 'Total price'; break;
        case 'total time': return (lang == 'es') ? 'Tiempo total' : 'Total time'; break;
        case 'assign prowasher': return (lang == 'es') ? 'Asignar prowasher' : 'Assign prowasher'; break;
        case 'billing activity code': return (lang == 'es') ? 'Codigo de activación de facturación' : 'Billing activity code'; break;
        case 'billing address': return (lang == 'es') ? 'Dirección de facturación' : 'Billing address'; break;
        case 'billing dni': return (lang == 'es') ? 'Identificación de facturación' : 'Billing dni'; break;
        case 'billing email': return (lang == 'es') ? 'Email de facturación' : 'Billing email'; break;
        case 'billing phone': return (lang == 'es') ? 'Telefono de facturación' : 'Billing phone'; break;
        case 'billing gyre': return (lang == 'es') ? 'Giro de facturación' : 'Billing gyre'; break;
        case 'billing required': return (lang == 'es') ? 'Facturación requerida' : 'Billing required'; break;
        case 'billing reason': return (lang == 'es') ? 'Razón de la facturación' : 'Billing reason'; break;
        case 'coupon list': return (lang == 'es') ? 'Lista de cupones' : 'Coupon list'; break;
        case 'coupon info': return (lang == 'es') ? 'Información de cupones' : 'Coupon info'; break;
        case 'coupons': return (lang == 'es') ? 'cupones' : 'Coupons'; break;
        case 'coupon': return (lang == 'es') ? 'cupon' : 'Coupon'; break;
        case 'discount': return (lang == 'es') ? 'Descuento' : 'Discount'; break;
        case 'order': return (lang == 'es') ? 'Orden' : 'Order'; break;

        // acciones generales {`${t("price")} A`}
        case 'hour': return (lang == 'es') ? 'Hora' : 'Hour'; break;
        case 'message detail': return (lang == 'es') ? 'Detalle del Mensaje' : 'Message Detail'; break;
        case 'create message': return (lang == 'es') ? 'Crear Mensaje' : 'Create Mesaage'; break;
        case 'sign in on the internal platform': return (lang == 'es') ? 'Iniciar sesión en la plataforma interna' : 'Sign in on the internal platform'; break;
        case 'sign in': return (lang == 'es') ? 'Iniciar Sessión' : 'Sign in'; break;
        case 'home': return (lang == 'es') ? 'Inicio' : 'Home'; break;
        case 'change': return (lang == 'es') ? 'Cambiar' : 'Change'; break;
        case 'good morning': return (lang == 'es') ? 'Buenos días' : 'Good mornig'; break;
        case 'here’s what’s happening with your projects today': return (lang == 'es') ? 'Esto es lo que está sucediendo con tus proyectos hoy' : 'Here’s what’s happening with your projects today'; break;
        case 'see all': return (lang == 'es') ? 'Ver Todos' : 'See All'; break;
        case 'notifications': return (lang == 'es') ? 'Notificaciones' : 'Notifications'; break;
        case 'pages': return (lang == 'es') ? 'Menu' : 'Pages'; break;
        case 'search': return (lang == 'es') ? 'Buscar' : 'Search'; break;
        case 'delete': return (lang == 'es') ? 'Borrar' : 'Delete'; break;
        case 'close': return (lang == 'es') ? 'Cerrar' : 'Close'; break;
        case 'save': return (lang == 'es') ? 'Guardar' : 'Save'; break;
        case 'view': return (lang == 'es') ? 'Ver' : 'View'; break;
        case 'sign out': return (lang == 'es') ? 'Salir' : 'Sign out'; break;
        case 'search': return (lang == 'es') ? 'Buscar' : 'Search'; break;
        case 'export': return (lang == 'es') ? 'Exportar' : 'Export'; break;
        case 'actions': return (lang == 'es') ? 'Acciones' : 'Actions'; break;
        case 'edit': return (lang == 'es') ? 'Editar' : 'Edit'; break;
        case 'add': return (lang == 'es') ? 'Agregar' : 'Add'; break;
        case 'disabled': return (lang == 'es') ? 'Deshabilitar' : 'Disabled'; break;
        case 'account': return (lang == 'es') ? 'Cuenta' : 'Account'; break;
        case 'data': return (lang == 'es') ? 'Datos' : 'Data'; break;
        case 'other actions': return (lang == 'es') ? 'Otras acciones' : 'Other actions'; break;
        case 'reset & send password': return (lang == 'es') ? 'Reiniciar y enviar contraseña' : 'Reset & send password'; break;
        case 'reset': return (lang == 'es') ? 'Reiniciar' : 'Reset'; break;
        case 'send password': return (lang == 'es') ? 'enviar contraseña' : 'send password'; break;
        case 'password': return (lang == 'es') ? 'Contraseña' : 'Password'; break;
        case 'disable': return (lang == 'es') ? 'Deshabilitar' : 'Disable'; break;
        case 'login as': return (lang == 'es') ? 'Loguear como' : 'Login as'; break;
   
        default: return word
    }

}

export default translate;